version: '2'

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "18081:8081"
    volumes_from:
      - nexus-data
    networks:
      - net-ci
  nexus-data:
    container_name: nexus-data
    image: sonatype/nexus:oss
    command: echo "data-only container for Nexus"
  jenkins:
    build: ./jenkins
    container_name: jenkins
    #image: jenkins
    links:
      - nexus
      - sonar
    volumes:
      - ./jenkins/home:/var/jenkins_home
    ports:
      - "18080:8080"
      - "50000:50000"
    networks:
      - net-ci
  sonar:
    image: sonarqube:5.6.1
    container_name: sonar
    ports:
      - "19000:9000"
    networks:
      - net-ci
networks:
  net-ci:
    driver: bridge
